spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?useUnicode=true&characterEncoding=UTF-8&serverTimezone=CST
    hikari:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
  application:
    name: content-center

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
server:
  port: 8010

logging:
  level:
    com.alibaba.study.contentcenter.feignclient.UserCenterFeignClient: debug


ribbon:
  eager-load:
    clients: user-center
    enabled: true

feign:
  client:
    config:
      # want call microservice name
      default:
        loggerLevel: full
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
  # Intellij idea does not display a prompt, but it is useful
  # Integer sentinel for feign
  sentinel:
    enabled: true

#ahas.namespace: default
#project.name: content-center
#ahas.license: 9399980bad5a4a9dba8b066bcd44d633



